# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8002
    servlet:
        context-path: /sys        session:          timeout: 7200
############################################################
#
# 配置数据源相关    使用 HikariCP 数据源
#
############################################################
spring:
  datasource:    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/smartsite?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: root
# Hikari will use the above plus the following to setup connection pooling
    type: com.zaxxer.hikari.HikariDataSource
    hikari:      connection-timeout: 30000 # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5  # 最小连接数
      maximum-pool-size: 15 # 最大连接数
      auto-commit: true  # 自动提交
      idle-timeout: 60000 # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DatebookHikariCP # 连接池名字
 # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms，建议设置比数据库超时时长少60秒，参考MySQL wait_timeout参数（show variables like '%timeout%';） -->
      max-lifetime: 28740000
      connection-test-query: SELECT 1
# Spring配置
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
logging:
    level:
       org.thymeleaf: info
#mybatis的扫描包路径
#mybatis-plus.mapper-locations=classpath:com/mht/springbootmybatisplus/mapper/xml/*.xml
#mybatis-plus.type-aliases-package=com.mht.springbootmybatisplus.entity
mybatis-plus:  configuration:    map-underscore-to-camel-case: true
